services:
  - type: web
    name: currency-converter
    env: node
    buildCommand: cd frontend && npm install && BUILD_PATH=dist npm run build
    startCommand: cd backend && npm install && node server.js
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./frontend/dist

